#!/bin/sh

# this script is part of MX Updater package
#
#
OPT="$1" ;

if  [ -f /usr/bin/mx-updater_unattended_upgrades_log_view ] && \
    [ -x /usr/bin/mx-updater_unattended_upgrades_log_view ] && \
    [ ! -L /usr/bin/mx-updater_unattended_upgrades_log_view ];
then
    : pass
else
    exit 1
fi


if [ "$OPT" = "--list" ]; then
    # list log files
    find /var/log/unattended-upgrades \
	-type f \
	-regextype egrep \
	-regex  '.*unattended-upgrades(-dpkg)?.log.*'
    exit 0
fi

# run log view

/usr/bin/mx-updater_unattended_upgrades_log_view | /usr/bin/cat

exit 0
