#!/bin/bash

# postinst script for mx-updater

if command -v py3compile >/dev/null 2>&1; then
	py3compile -p mx-updater /usr/libexec/mx-updater  || true
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p mx-updater /usr/libexec/mx-updater || true
fi


case "$1" in
  configure)  
	#remove obsolete /etc/apt/apt.conf.d/15periodic-update file 
	rm -f /etc/apt/apt.conf.d/15periodic-update
	
	#if /etc/cron.daily/apt~ exists rename it back to /etc/cron.daily/apt
	if [ -f /etc/cron.daily/apt~ ] && [ ! -f /etc/cron.daily/apt ]; then
		mv /etc/cron.daily/apt~ /etc/cron.daily/apt
	fi
	
	if  [ ! -f /etc/apt/apt.conf.d/02periodic ]
	then
	  cp /usr/share/mx-updater/02periodic /etc/apt/apt.conf.d/02periodic
	  sed -i '/overwrite existing/d' /etc/apt/apt.conf.d/02periodic
	else
	  if [ "$(sed '/overwrite existing/d' /usr/share/mx-updater/02periodic | md5sum)" = "$(cat /etc/apt/apt.conf.d/02periodic | md5sum)" ]
		then
		  :
		else
		  grep -q 'overwrite existing' /usr/share/mx-updater/02periodic
		  if [ $? -eq 0 ]
			then
			  cp /usr/share/mx-updater/02periodic /etc/apt/apt.conf.d/02periodic
			  sed -i '/overwrite existing/d' /etc/apt/apt.conf.d/02periodic
			else
			  :
		  fi
	  fi       
	fi
	if  [ ! -f /etc/apt/apt.conf.d/51unattended-upgrades-config ] && \
	    [ -f /usr/share/mx-updater/51unattended-upgrades-config ]; then
		  cp /usr/share/mx-updater/51unattended-upgrades-config \
		     /etc/apt/apt.conf.d/51unattended-upgrades-config 2>/dev/null || :
	fi

	if  [ ! -f /etc/xdg/autostart/mx-updater-autostart.desktop   ] && \
	    [  -f /usr/share/mx-updater/mx-updater-autostart.desktop ]; then
	    cp /usr/share/mx-updater/mx-updater-autostart.desktop /etc/xdg/autostart/mx-updater-autostart.desktop  || true
	fi

	if  [ -f /usr/share/mx-updater/51unattended-upgrades-default-origins ]; then
	    if  [ -f /etc/apt/apt.conf.d/51unattended-upgrades-default-origins ]; then
	       rm -f /etc/apt/apt.conf.d/51unattended-upgrades-default-origins || :
	    fi
	    cp /usr/share/mx-updater/51unattended-upgrades-default-origins \
	       /etc/apt/apt.conf.d/51unattended-upgrades-default-origins 2>/dev/null || :
	fi

	if  [ -f /usr/share/mx-updater/51unattended-upgrades-blacklist ]; then
	    if  [ -f /etc/apt/apt.conf.d/51unattended-upgrades-blacklist ]; then
	       rm -f /etc/apt/apt.conf.d/51unattended-upgrades-blacklist || :
	    fi
	    cp /usr/share/mx-updater/51unattended-upgrades-blacklist \
	       /etc/apt/apt.conf.d/51unattended-upgrades-blacklist 2>/dev/null || :
	fi

	
	;;
esac
exit 0

